[versions]
agp = "9.0.0"
blurviewVersion = "version-2.0.5"
compiler = "5.0.5"
glide = "5.0.5"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.12.3"
constraintlayout = "2.2.1"
core = "1.17.0"
fragment = "1.8.9"
navigationFragmentKtx = "2.9.7"
navigationUiKtx = "2.9.7"
animated-bottom-bar = "1.1.0"
okhttp = "5.3.2"
retrofit = "3.0.0"
roomRuntime = "2.8.4"
rxandroid = "3.0.2"
rxjava = "3.1.12"
retrofit-adapter-rxjava3 = "3.0.0"
refresh-layout = "1.2.0"


[libraries]
blurview-vversion = { module = "com.github.Dimezis:BlurView", version.ref = "blurviewVersion" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "compiler" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
navigation-safe-args-gradle-plugin = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "navigationFragmentKtx" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
core = { group = "androidx.core", name = "core", version.ref = "core" }
fragment = { group = "androidx.fragment", name = "fragment", version.ref = "fragment" }
navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }
animated-bottom-bar = {group = "nl.joery.animatedbottombar", name = "library", version.ref="animated-bottom-bar"}
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
rxandroid = { module = "io.reactivex.rxjava3:rxandroid", version.ref = "rxandroid" }
rxjava = { module = "io.reactivex.rxjava3:rxjava", version.ref = "rxjava" }
retrofit-adapter-rxjava3 = { module = "com.squareup.retrofit2:adapter-rxjava3", version.ref = "retrofit-adapter-rxjava3" }
refresh-layout = {group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "refresh-layout"}

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
safe-args = {id = "androidx.navigation.safeargs" }